#This file is only to generate model class, the structure was imported automatically from Realmd Database, but it's wrong.
#They're missing indexes, wring type, etc.
#You must use sql from MaNGOS Project
Account:
  columns:
    id: { type: integer(11), unsigned: true, primary: true, autoincrement: true }
    username: { type: string(32), default: '', notnull: true, unique: true }
    sha_pass_hash: { type: string(40), default: '', notnull: true }
    gmlevel: { type: integer(1), unsigned: true, default: 0, notnull: true }
    sessionkey: { type: string() }
    v: { type: string() }
    s: { type: string() }
    email: { type: string() }
    joindate: { type: timestamp(25), notnull: true, default: CURRENT_TIMESTAMP }
    last_ip: { type: string(30), default: 0.0.0.0, notnull: true }
    failed_logins:
      type: integer(4)
      unsigned: true
      default: '0'
      notnull: true
    locked:
      type: integer(1)
      unsigned: true
      default: '0'
      notnull: true
    last_login:
      type: timestamp(25)
      default: '0000-00-00 00:00:00'
      notnull: true
    active_realm_id:
      type: integer(4)
      unsigned: true
      default: '0'
      notnull: true
    expansion:
      type: integer(1)
      unsigned: true
      default: '0'
      notnull: true
    mutetime:
      type: integer(8)
      unsigned: true
      default: '0'
      notnull: true
    locale:
      type: integer(1)
      unsigned: true
      default: '0'
      notnull: true
AccountBanned:
  columns:
    id:
      type: integer(4)
      primary: true
    bandate:
      type: integer(8)
      primary: true
    unbandate:
      type: integer(8)
      default: '0'
      notnull: true
    bannedby:
      type: string(50)
      notnull: true
    banreason:
      type: string(255)
      notnull: true
    active:
      type: integer(1)
      default: '1'
      notnull: true

IpBanned:
  columns:
    ip:
      type: string(32)
      primary: true
    bandate:
      type: integer(8)
      primary: true
    unbandate:
      type: integer(8)
      notnull: true
    bannedby:
      type: string(50)
      default: '[Console]'
      notnull: true
    banreason:
      type: string(255)
      default: 'no reason'
      notnull: true