<?php include('schemaConfig.php') ?>
---
sfGuardUser:
  tableName: <?php echo $config['user_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    username:
      type: string
      size: 128
      notnull: true
      unique: true
    algorithm:
      type: string
      size: 128
      default: sha1
      notnull: true
    salt:
      type: string
      size: 128
      notnull: true
    password:
      type: string
      size: 128
      notnull: true
    last_login:
      type: timestamp
    is_active:
      type: boolean
      default: 1
      notnull: true
    is_super_admin:
      type: boolean
      default: 0
      notnull: true
  relations:
    permissions:
      class: sfGuardPermission
      foreignAlias: users
      refClass: sfGuardUserPermission
      local: user_id
      foreign: permission_id
    groups:
      class: sfGuardGroup
      foreignAlias: users
      refClass: sfGuardUserGroup
      local: user_id
      foreign: group_id

sfGuardUserGroup:
  tableName: <?php echo $config['user_group_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    group_id:
      type: integer
      size: 4
      primary: true
    user_id:
      type: integer
      size: 4
      primary: true
  relations:
    sfGuardGroup:
      class: sfGuardGroup
      local: group_id
    sfGuardUser:
      class: sfGuardUser
      local: user_id

sfGuardUserPermission:
  tableName: <?php echo $config['user_permission_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    user_id:
      type: integer
      size: 4
      primary: true
    permission_id:
      type: integer
      size: 4
      primary: true
  relations:
    sfGuardUser:
      class: sfGuardUser
      local: user_id
    sfGuardPermission:
      class: sfGuardPermission
      local: permission_id

sfGuardGroup:
  tableName: <?php echo $config['group_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    name:
      type: string
      size: 255
      notnull: true
    description:
      type: string
      size: 4000
  relations:
    permissions:
      class: sfGuardPermission
      refClass: sfGuardGroupPermission
      local: group_id
      foreign: permission_id
    users:
      class: sfGuardUser
      refClass: sfGuardUserGroup
      local: group_id
      foreign: user_id

sfGuardGroupPermission:
  tableName: <?php echo $config['group_permission_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    group_id:
      type: integer
      size: 4
      notnull: true
      primary: true
    permission_id:
      type: integer
      size: 4
      notnull: true
      primary: true
  relations:
    sfGuardGroup:
      class: sfGuardGroup
      local: group_id
    sfGuardPermission:
      class: sfGuardPermission
      local: permission_id

sfGuardPermission:
  tableName: <?php echo $config['permission_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    name:
      type: string
      size: 255
      notnull: true
    description:
      type: string
      size: 4000
  relations:
    groups:
      class: sfGuardGroup
      refClass: sfGuardGroupPermission
      local: permission_id
      foreign: group_id
    users:
      class: sfGuardUser
      refClass: sfGuardUserPermission
      local: permission_id
      foreign: user_id

sfGuardRememberKey:
  tableName: <?php echo $config['remember_key_table']."\n"; ?>
  package: sfGuardDoctrinePlugin.lib.model.doctrine
  templates: [ Doctrine_Template_Timestampable ]
  columns:
    id:
      type: integer
      size: 4
      primary: true
      autoincrement: true
    created_at:
      type: timestamp
    updated_at:
      type: timestamp
    user_id:
      type: integer
      size: 4
      primary: true
    remember_key:
      type: string
      size: 32
    ip_address:
      type: string
      size: 15
      primary: true
  relations:
    user:
      class: sfGuardUser
      alias: user
      foreignAlias: remember_key
      onDelete: CASCADE
      local: user_id