<?php include('schemaConfig.php') ?>
---
sfGuardUser:
  tableName: <?php echo $config['user_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    username:
      type: string(128)
      notnull: true
      unique: true
    algorithm:
      type: string(128)
      default: sha1
      notnull: true
    salt:
      type: string(128)
      notnull: true
    password:
      type: string(128)
      notnull: true
    last_login:
      type: timestamp
    is_active:
      type: boolean
      default: 1
      notnull: true
    is_super_admin:
      type: boolean
      default: 0
      notnull: true
  relations:
    permissions:
      class: sfGuardPermission
      foreignAlias: users
      refClass: sfGuardUserPermission
      local: user_id
      foreign: permission_id

    groups:
      class: sfGuardGroup
      foreignAlias: users
      refClass: sfGuardUserGroup
      local: user_id
      foreign: group_id

sfGuardUserGroup:
  tableName: <?php echo $config['user_group_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer(4)
      primary: true
    user_id:
      type: integer(4)
      primary: true
  relations:
    group:
      class: sfGuardGroup
      local: group_id
      onDelete: CASCADE
    user:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE

sfGuardUserPermission:
  tableName: <?php echo $config['user_permission_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer(4)
      primary: true
    permission_id:
      type: integer(4)
      primary: true
  relations:
    user:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
    permission:
      class: sfGuardPermission
      local: permission_id
      onDelete: CASCADE

sfGuardGroup:
  tableName: <?php echo $config['group_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: string(4000)
  relations:
    permissions:
      class: sfGuardPermission
      refClass: sfGuardGroupPermission
      local: group_id
      foreign: permission_id
    users:
      class: sfGuardUser
      refClass: sfGuardUserGroup
      local: group_id
      foreign: user_id

sfGuardGroupPermission:
  tableName: <?php echo $config['group_permission_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer(4)
      notnull: true
      primary: true
    permission_id:
      type: integer(4)
      notnull: true
      primary: true
  relations:
    group:
      class: sfGuardGroup
      local: group_id
      onDelete: CASCADE
    permission:
      class: sfGuardPermission
      local: permission_id
      onDelete: CASCADE

sfGuardPermission:
  tableName: <?php echo $config['permission_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: string(4000)
  relations:
    groups:
      class: sfGuardGroup
      refClass: sfGuardGroupPermission
      local: permission_id
      foreign: group_id
    users:
      class: sfGuardUser
      refClass: sfGuardUserPermission
      local: permission_id
      foreign: user_id

sfGuardRememberKey:
  tableName: <?php echo $config['remember_key_table']."\n"; ?>
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      primary: true
    remember_key:
      type: string(32)
    ip_address:
      type: string(15)
      primary: true
  relations:
    user:
      class: sfGuardUser
      alias: user
      foreignAlias: remember_key
      onDelete: CASCADE
      local: user_id