sfGuardRememberKey:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer(11)
      unsigned: true
      notnull: true
    remember_key: string(32)
    ip_address: string(50)
  relations:
    User:
      class: Account
      local: user_id
      foreignAlias: RememberKeys
      foreignType: one

sfGuardForgotPassword:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [Timestampable]
  columns:
    user_id:
      type: integer(11)
      unsigned: true
      notnull: true
    unique_key: string(255)
    expires_at:
      type: timestamp
      notnull: true
  relations:
    User:
      class: Account
      local: user_id
      type: one
      foreignType: one
      foreignAlias: ForgotPassword
